# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_customer_list', '可以查看客户列表'), ('view_customer_info', '可以查看客户详情'), ('edit_customer_info', '可以修改客户信息'), ('view_new_customer', '可以查看新客户信息'), ('add_new_customer', '可以添加新客户信息'), ('del_customer_info', '可以删除用户信息')), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
